# docker-compose.yml
version: "3.2"
networks:
  backend:

services:
  server:
    container_name: flask
    build:
      context: .  # here changed
      dockerfile: ./docker/python/Dockerfile
    ports:
      - '81:5000'
    expose:
      - '81'
    volumes: ['.:/usr/src/app']
    restart: always
    environment:
      ENV: DEVELOPMENT
      DB_USERNAME: loganus
      DB_PASSWORD: loganpw
      DB_DATABASE: logan
      DB_HOST: database
    links:
      - database
    networks:
        - backend

  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: "loganpw"
      MYSQL_DATABASE: "logan"
      MYSQL_USER: "loganus"
      MYSQL_PASSWORD: "loganpw"
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - flask-db:/var/lib/mysql
    networks:
      - backend

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    links:
      - database
    networks:
      - backend

volumes:
  flask-db: